/**: # Global Params
  ros__parameters:
    traj_name: 'cut_square.json'

NAND:
  bnyahaj:
    ros__parameters:
      teensy_name: 'ttyUSB0'

  NAND_controller:
    ros__parameters:
      dist: 0.0
      stateTopic: 'self/state'
      trajectoryTopic: 'self/cur_traj'
      steeringTopic: 'input/steering'
      rawSteeringTopic: "input/steering_raw"
      steerOffsetTopic: "self/steering_offset/filtered"
      useSteerOffset: false 
      useHeadingRate: true
      controllerName: 'controller'
      controller: 'stanley'
