/**: # Global Params
  ros__parameters:
      traj_name: "buggycourse_nand.json"

NAND:
  bnyahaj:
    ros__parameters:
      teensy_name: "ttyUSB0"

  NAND_controller:
    ros__parameters:
      dist: 0.0
      stateTopic: "self/state"
      trajectoryTopic: "self/cur_traj"
      steeringTopic: "input/steering"
      rawSteeringTopic: "input/steering_raw"
      steerOffsetTopic: "self/steering_offset/filtered"
      useSteerOffset: false 
      useHeadingRate: true
      controllerName: "controller"
      controller: "stanley"

  NAND_offset_estimator:
    ros__parameters:
      steerOffsetRawTopic: "self/steering_offset/raw"
      steerOffsetFilteredTopic: "self/steering_offset/filtered"
      steerOffsetFilterTimeConstant: 1   # in timesteps; smoothing factor alpha for low pass filter is 1 / steerOffsetFilterTimeConstant
